// Issue #1542 — enforced ESLint + React Hooks gate.
//
// Scope (deliberately narrow):
//   * TypeScript correctness rules (high signal only — no cosmetic flood).
//   * react-hooks/rules-of-hooks at `error` (issue acceptance criterion).
//   * react-hooks/exhaustive-deps at `warn` (we surface every miss and
//     promote cases the team agrees on; see docs/agents/engineering.md
//     for the "review baseline" pattern that justified this choice).
//
// Excluded by design (NOT mass-disabled — each line names its reason):
//   * src/types/generated/**   — generated by ts-rs from Rust #[derive(TS)]
//                                during `cargo test`. Drift is gated by a
//                                separate CI step that diffs the directory
//                                against the Rust emit (issue #359).
//   * dist/**                  — build output, never read by lint.
//   * node_modules/**          — third-party.
//   * coverage/**, .tmp/**     — scratch dirs.
//
// Globals scoping (issue acceptance):
//   * `src/**` gets browser globals (window, document, fetch, …) — this
//     is the Tauri WebView surface.
//   * `tests/**`, `scripts/**`, `*.config.{js,ts}`, and `tests/agent-infra/**`
//     get node globals + vitest globals (describe/it/expect). Mixing the
//     two would let test-only globals leak into UI code, which is the
//     exact opposite of the scoping the issue asked for.

import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';
import globals from 'globals';

export default tseslint.config(
  {
    // `reportUnusedDisableDirectives: 'error'` makes every stale
    // `// eslint-disable-next-line …` comment fail lint instead of
    // silently masking a rule that no longer fires (review feedback on
    // PR #1635 — this is what caught the inert directives I had
    // sprinkled over empty switch fall-throughs and the FileTree
    // `new Map(...)` line). Cost: zero at runtime, a one-time
    // backfill pain to clean up obsolete disables.
    linterOptions: {
      reportUnusedDisableDirectives: 'error',
    },
  },
  {
    ignores: [
      'src/types/generated/**',
      'dist/**',
      'node_modules/**',
      'coverage/**',
      '.tmp/**',
      // Agent infrastructure (PreToolUse / PostToolUse hook scripts).
      // They live in this repo so version-controlled changes can ship
      // with the rest of the tooling, but they're not authored against
      // this ESLint config and have their own `process.env` / hook
      // contract checks.
      '.claude/hooks/**',
      // The fixture under tests/agent-infra/fixtures/ exists to PROVE
      // the gate catches what it claims to catch (issue #1542 acceptance:
      // "Fixtures with conditional Hooks or missing effect dependencies
      // must fail lint"). The fixture deliberately violates
      // react-hooks/rules-of-hooks + exhaustive-deps; if the default
      // `eslint .` pass lints it, the gate can never go green. The
      // companion gate test (tests/agent-infra/eslint-config-gate.test.mjs)
      // constructs an ESLint instance with `ignore: false` to lint THIS
      // file specifically — see the test's comment.
      'tests/agent-infra/fixtures/**',
    ],
  },

  // Base — every JS/TS file under the repo gets TypeScript-aware linting,
  // the recommended ruleset baseline, and (when in src/) browser globals.
  // We extend the base with file-globbed overrides further down so the
  // "where do Node globals come from?" answer stays in one place.
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    plugins: {
      'react-hooks': reactHooks,
    },
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        ...globals.browser,
      },
    },
    rules: {
      // React Hooks — the headline gate. Acceptance: "rules-of-hooks as
      // an error". exhaustive-deps stays at warn because it surfaces a
      // LOT of existing misses; the team promotes specific cases to
      // error after reviewing them, not the other way around.
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',

      // High-signal TypeScript correctness (syntactic-only — we do NOT
      // enable the type-aware preset because it requires every linted
      // file to belong to the same tsconfig project, which triples
      // lint time and breaks the "fast gate" goal of this issue).
      // `no-floating-promises` and `no-misused-promises` are deliberately
      // omitted here; revisit when the project gains a typed-linting
      // harness (separate issue, separate cost/benefit decision).
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-empty-function': 'off', // see `no-empty-function` above
      '@typescript-eslint/no-require-imports': 'warn',
      '@typescript-eslint/no-unused-vars': [
        'warn',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],

      // General correctness — narrow, high-signal.
      // `no-console` / `no-eval` / `no-empty-function` are intentionally
      // OFF in TS/TSX (TS handles unused vars + types; these are pure
      // style):
      //   * no-console: pure style; `console.warn` is a legitimate
      //     fallback in lib/pathInvalidatedCache.ts and tests/integration.
      //   * no-eval: only used by the test mock harness; the call site is
      //     already isolated in tests/unit/tauri-mock-harness.test.ts.
      //   * no-empty-function: a flood of test-fixture vi.fn(() => {})
      //     callbacks would be the entire signal — zero bugs caught.
      // `no-undef` is enabled per-file in the JS override block below
      // (PR #1635 review feedback: turning it off globally made the
      // browser-vs-Node globals scoping decorative — typed files have
      // TS coverage; JS files (notably the OpenCode attention plugin)
      // don't).
      'no-console': 'off',
      'no-eval': 'off',
      'no-empty-function': 'off',
      'no-debugger': 'error',
      'no-fallthrough': 'error',
      'no-constant-condition': ['warn', { checkLoops: false }],
      'prefer-const': 'warn',

      // Skip rules that conflict with the recommended TS preset or are
      // pure style — Prettier owns style, ESLint owns correctness.
      'no-unused-vars': 'off', // superseded by @typescript-eslint/no-unused-vars above
      '@typescript-eslint/no-unused-expressions': 'off', // common in JSX render guards
    },
  },

  // ── UI source ─────────────────────────────────────────────────────────────
  // The frontend (src/** + mobile/** + tests/unit/** + tests/integration/**)
  // gets React Hooks rules but tests also need their own globals and
  // slightly relaxed TS rules so vitest fixtures (e.g. `as any`, `eval`)
  // can be expressed honestly. Production UI source never sees node globals.
  //
  // `no-undef` is OFF here because the TypeScript checker already
  // catches undefined references AND the TS lib types
  // (`RequestInit`, `ResizeObserverCallback`, `React` under the
  // react-jsx transform, etc.) aren't exposed to ESLint's globals
  // registry — turning the rule on would surface ~80 false positives
  // (PR #1635 review feedback). The plain-JS override below is the
  // only place we keep `no-undef: 'error'`, and only because the JS
  // file it targets has no TypeScript coverage at all.
  {
    files: ['src/**/*.{ts,tsx}', 'mobile/**/*.{ts,tsx}'],
    languageOptions: {
      globals: {
        ...globals.browser,
      },
    },
    rules: {
      'no-undef': 'off',
    },
  },

  // ── Test source ───────────────────────────────────────────────────────────
  // Vitest globals + node globals (some integration tests poke at
  // process/Buffer). Production TS rules still apply, but `no-explicit-any`
  // is suppressed — vitest fixture setup code regularly uses `as any` to
  // install mocks (jsdom's window, Tauri __TAURI_INTERNALS__, …).
  //
  // `no-undef` is OFF here too — the same TS-lib-types problem from the
  // UI override applies, and vitest fixture setup often references TS
  // types (`RequestInit`, `NodeJS`, etc.) that ESLint can't see.
  {
    files: ['tests/**/*.{ts,tsx,mts,mjs,js}', 'src/**/*.test.{ts,tsx}'],
    languageOptions: {
      globals: {
        ...globals.node,
        ...globals.browser,
        // Vitest globals (also declared via tsconfig types, but lint
        // doesn't read tsconfig types so we re-declare here).
        describe: 'readonly',
        it: 'readonly',
        test: 'readonly',
        expect: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        beforeAll: 'readonly',
        afterAll: 'readonly',
        vi: 'readonly',
        vitest: 'readonly',
      },
    },
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
      'no-console': 'off',
      'no-eval': 'off',
      'no-undef': 'off',
    },
  },

  // ── Scripts + infra config ────────────────────────────────────────────────
  // scripts/*.mjs and *.config.{js,ts} are Node code. React Hooks rules
  // do nothing meaningful here (no JSX) but don't hurt either.
  {
    files: ['scripts/**/*.{js,mjs,cjs,ts}', '*.config.{js,ts,mjs}', 'vite.config.ts', 'vitest.config.ts', 'playwright.config*.ts', 'src/vite-env.d.ts'],
    languageOptions: {
      globals: {
        ...globals.node,
      },
    },
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      'no-console': 'off', // these are CLI scripts; console IS the UI.
    },
  },

  // ── Plain JS files (no TypeScript coverage) ──────────────────────────────
  // Most of the repo is TS/TSX and is covered by the TypeScript checker
  // for undefined-reference detection. The notable exception is
  // `src-tauri/src/agent/provider/adapters/opencode_attention_plugin.js`
  // — an ESM module loaded by the OpenCode TUI at runtime. It's
  // shipped as plain `.js` (no `tsc` compile step), so it has zero
  // type coverage outside ESLint. We enable `no-undef` here and seed
  // Node + browser globals so a typo in `process.env.X` actually
  // surfaces as a lint error instead of silently passing a `undefined`
  // into the network layer. (PR #1635 review feedback.)
  //
  // Posix patterns only — negation patterns (`!**/*.test.js`) caused
  // the override to apply to `.tsx` files too during testing, which
  // surfaces ~80 false positives for TS lib types that aren't in
  // ESLint's globals registry.
  {
    files: ['src-tauri/**/*.js'],
    languageOptions: {
      globals: {
        ...globals.node,
        ...globals.browser,
      },
    },
    rules: {
      'no-undef': 'error',
    },
  },

  // ── The intentional-violations fixture ────────────────────────────────────
  // The fixture under tests/agent-infra/fixtures/ is excluded by the
  // top-level `ignores` block above — the companion gate test
  // (tests/agent-infra/eslint-config-gate.test.mjs) re-introduces it
  // via `new ESLint({ ignore: false })` to assert the configured rules
  // actually flag the violations. The fixture MUST remain in the repo
  // and MUST continue to violate rules-of-hooks + exhaustive-deps.
);
